const Program=require('../models/Program');
const Batch=require('../models/Batch');
const Plan=require('../models/Plan');
const Faq=require('../models/ProgramFaq');
const Content=require('../models/AppContent');
const News=require('../models/SimpleNews');
const Video=require('../models/LiveContent');
const Testimonial=require('../models/Testimonial');
const Notification=require('../models/Notification');
const Module=require('../models/Module');
const {visibleAudiences}=require('../utils/notificationAudience');
const {availableEnrollment}=require('../utils/availableEnrollment');
const {fail,handle,list,regex,text,profile}=require('../utils/appApi');
const {normalizeMaterialLink}=require('../utils/materialLink');
const defaults={version:'1.0.1',phone:'',email:'',whatsapp:'',androidUrl:'',iosUrl:'',shareUrl:'',banners:[]};
async function content(key){const doc=await Content.findById(key).lean();return doc?.data;}
async function config(){return {...defaults,...await content('config')};}
function programDto(p,req){const selling=p.discountedPrice==null?p.price:p.discountedPrice;return {id:p._id,title:text(req,p.programName,p.programNameHindi),category:p.programCategory,year:p.year,image:p.displayImage,description:text(req,p.description,p.descriptionHindi),overview:text(req,p.overview,p.overviewHindi)||text(req,p.description,p.descriptionHindi),features:req.query.lang==='hi'&&p.featuresHindi?.some(Boolean)?p.featuresHindi:p.features||[],medium:p.medium||'Bilingual',startDate:p.startDate,endDate:p.endDate,duration:text(req,p.duration,p.durationHindi),price:{currency:'INR',original:p.price,selling,onSale:selling<p.price},isNew:Date.now()-new Date(p.createdAt).getTime()<30*86400000,accessType:p.accessType||null};}
function filterPrograms(query){const filter=availableEnrollment();if(query.group==='mentorship')filter.programCategory={$in:['Mentorship Course','Optional Mentorship Course']};if(query.group==='test-series')filter.programCategory={$in:['Test Series','Optional Test Series']};if(query.category)filter.programCategory=query.category;if(query.year)filter.year=query.year;if(query.search)filter.$or=[{programName:{$regex:regex(query.search),$options:'i'}},{programNameHindi:{$regex:regex(query.search),$options:'i'}}];if(query.medium)filter.medium=query.medium;return filter;}
const getProgram=async id=>{const p=await Program.findOne({_id:id,...availableEnrollment()}).lean();if(!p)throw fail(404,'Active program not found.');return p;};
exports.config=handle(async(req,res)=>res.json({success:true,data:await config()}));
exports.onboarding=handle(async(req,res)=>res.json({success:true,data:await content('onboarding')||[]}));
exports.support=handle(async(req,res)=>{const c=await config();res.json({success:true,data:{phone:c.phone,email:c.email,whatsappUrl:c.whatsapp?'https://wa.me/'+c.whatsapp.replace(/\D/g,''):null,version:c.version}});});
exports.share=handle(async(req,res)=>{const c=await config();res.json({success:true,data:{text:'ThinkCivil IAS',url:c.shareUrl||c.androidUrl||c.iosUrl||null,androidUrl:c.androidUrl||null,iosUrl:c.iosUrl||null}});});
exports.legal=handle(async(req,res)=>res.json({success:true,data:await content(req.params.kind)||{title:req.params.kind==='terms'?'Terms & Conditions':'Privacy Policy',body:'',url:null,published:false}}));
exports.faqs=handle(async(req,res)=>{let data=await content('faqs')||[];if(req.query.programId){await getProgram(req.query.programId);data=await Faq.find({programId:req.query.programId,isActive:true}).sort({order:1}).lean();}res.json({success:true,data:data.map(f=>({id:f._id||f.id,question:text(req,f.question,f.questionHindi),answer:text(req,f.answer,f.answerHindi)}))});});
exports.programs=handle(async(req,res)=>{const sorts={newest:{createdAt:-1,_id:1},name:{programName:1,_id:1},startDate:{startDate:1,_id:1}};if(['price_asc','price_desc'].includes(req.query.sort)){const p=require('../utils/appApi').page(req.query);const result=await Program.aggregate([{$match:filterPrograms(req.query)},{$addFields:{sellingPrice:{$ifNull:['$discountedPrice','$price']}}},{$sort:{sellingPrice:req.query.sort==='price_asc'?1:-1,_id:1}},{$facet:{data:[{$skip:p.skip},{$limit:p.limit}],total:[{$count:'count'}]}}]);const total=result[0]?.total[0]?.count||0;return res.json({success:true,data:(result[0]?.data||[]).map(x=>programDto(x,req)),pagination:{page:p.page,limit:p.limit,total,pages:Math.ceil(total/p.limit)}});}await list(Program,filterPrograms(req.query),req,res,sorts[req.query.sort]||{order:1,createdAt:-1},null,p=>programDto(p,req));});
exports.filters=handle(async(req,res)=>{const filter=availableEnrollment();const[categories,years,mediums]=await Promise.all(['programCategory','year','medium'].map(field=>Program.distinct(field,filter)));res.json({success:true,data:{categories,years,mediums,sorts:['newest','name','startDate','price_asc','price_desc']}});});
exports.program=handle(async(req,res)=>{const p=await getProgram(req.params.id);const faqs=await Faq.find({programId:p._id,isActive:true}).sort({order:1}).lean();res.json({success:true,data:{...programDto(p,req),faqs:faqs.map(f=>({id:f._id,question:text(req,f.question,f.questionHindi),answer:text(req,f.answer,f.answerHindi)})),support:await config()}});});
exports.batches=handle(async(req,res)=>{await getProgram(req.params.id);await list(Batch,{programId:req.params.id,...availableEnrollment()},req,res,{order:1,startDate:1},'-createdBy -updatedBy -__v',b=>({...b,title:text(req,b.batchName,b.batchNameHindi)}));});
exports.brochure=handle(async(req,res)=>{await getProgram(req.params.id);const b=await Batch.findOne({_id:req.params.batchId,programId:req.params.id,...availableEnrollment()}).lean();if(!b)throw fail(404,'Batch not found.');const url=req.query.lang==='hi'?b.brochureHindi:b.brochureEnglish;if(!url)throw fail(404,'Brochure is not available in this language.');res.json({success:true,data:{url:normalizeMaterialLink(url)}});});
exports.plans=handle(async(req,res)=>list(Plan,{isActive:true},req,res,{displayOrder:1},'-__v'));
exports.news=handle(async(req,res)=>list(News,{isActive:true},req,res,{createdAt:-1},'-createdBy',n=>({id:n._id,text:text(req,n.text,n.textHi)})));
exports.videos=handle(async(req,res)=>list(Video,{isActive:true},req,res,{createdAt:-1},'-createdBy -__v'));
exports.testimonials=handle(async(req,res)=>list(Testimonial,{isActive:true},req,res,{createdAt:-1},'-__v',t=>({...t,name:text(req,t.name,t.nameHindi),description:text(req,t.description,t.descriptionHindi),subtitle:text(req,t.subtitle,t.subtitleHindi)})));
function resourceDto(item,req){return {id:item._id,name:text(req,item.name?.english,item.name?.hindi),type:item.type==='file'?'file':'folder',image:item.image||null,fileType:item.type==='file'?item.fileType||'other':null,url:item.type==='file'?item.fileLink||null:null,parentId:item.parent||null};}
exports.resources=handle(async(req,res)=>{const filter={isActive:true,parent:req.query.parentId||null};await list(Module,filter,req,res,{order:1,'name.english':1},'-createdBy -__v -quizId -moduleTestId',m=>resourceDto(m,req));});
exports.resource=handle(async(req,res)=>{const item=await Module.findOne({_id:req.params.id,isActive:true}).select('-createdBy -__v').lean();if(!item)throw fail(404,'Resource not found.');res.json({success:true,data:resourceDto(item,req)});});
exports.dashboard=handle(async(req,res)=>{const[mentorship,testSeries,plans,news,videos,testimonials,settings,unread]=await Promise.all([Program.find(filterPrograms({group:'mentorship'})).sort({order:1}).limit(6).lean(),Program.find(filterPrograms({group:'test-series'})).sort({order:1}).limit(6).lean(),Plan.find({isActive:true}).sort({displayOrder:1}).limit(6).lean(),News.find({isActive:true}).sort({createdAt:-1}).limit(10).lean(),Video.find({isActive:true}).sort({createdAt:-1}).limit(6).lean(),Testimonial.find({isActive:true}).sort({createdAt:-1}).limit(6).lean(),config(),Notification.countDocuments({audience:{$in:visibleAudiences(req.user.type)},readBy:{$ne:req.user._id}})]);res.json({success:true,data:{user:profile(req.user),unreadNotifications:unread,banners:settings.banners,mentorship:mentorship.map(p=>programDto(p,req)),testSeries:testSeries.map(p=>programDto(p,req)),plans,news:news.map(n=>({id:n._id,text:text(req,n.text,n.textHi)})),videos,testimonials,support:settings}});});
exports.getConfig=config;
